version: 2

references:
    restore_dependencies_cache: &restore_dependencies_cache
        restore_cache:
            key: v1-deps-{{ checksum "composer.json" }}

    install_dependencies: &install_dependencies
        run: composer install

    save_dependencies_cache: &save_dependencies_cache
        save_cache:
            paths: [./vendor]
            key: v1-deps-{{ checksum "composer.json" }}

    restore_phpunit_cache: &restore_phpunit_cache
        restore_cache:
            key: v1-phpunit-{{ checksum "composer.json" }}

    install_phpunit: &install_phpunit
        run: php vendor/bin/simple-phpunit install

    save_phpunit_cache: &save_phpunit_cache
        save_cache:
            paths: [./bin/.phpunit]
            key: v1-phpunit-{{ checksum "composer.json" }}

    run_tests: &run_tests
        resource_class: small
        steps:
            - checkout

            # Dependencies
            - *restore_dependencies_cache
            - *install_dependencies
            - *save_dependencies_cache

            # Install PHPUnit
            - *restore_phpunit_cache
            - *install_phpunit
            - *save_phpunit_cache

            # Run the tests
            - run: php vendor/bin/simple-phpunit -v --log-junit ./phpunit/junit.xml
            - store_test_results:
                  path: ./phpunit

jobs:
    php-cs:
        docker:
            - image: php:7.2-cli-alpine
        resource_class: small
        steps:
            - checkout
            - run: wget https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/v2.13.1/php-cs-fixer.phar
            - run: php php-cs-fixer.phar fix --dry-run --diff

    tests-php-7-1:
        docker:
            - image: circleci/php:7.1
        <<: *run_tests

    tests-php-7-2:
        docker:
            - image: circleci/php:7.2
        <<: *run_tests

    tests-php-7-3:
        docker:
            - image: circleci/php:7.3
        <<: *run_tests

    tests-php-7-4:
        docker:
            - image: circleci/php:7.4
        <<: *run_tests

workflows:
    version: 2
    test:
        jobs:
            - php-cs
            - tests-php-7-1
            - tests-php-7-2
            - tests-php-7-3
            - tests-php-7-4
